version: '3.9'

services:
  db:
    image: postgres:15.0-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  fastapi:
    build:
      context: ./dummy_fastapi_flask_blog_app
      dockerfile: ./uvicorn_fastapi/Dockerfile
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  bats:
    build:
      context: .
      dockerfile: client_bats.Dockerfile
    container_name: bats
    depends_on:
      - db
      - fastapi
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./api_clients/bash:/app

networks:
  app-network:
    driver: bridge
