name: Bats Test

on: [push, pull_request]

jobs:
  run_bats_test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5432:5432
          - 8000:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Set a env file
      run: |
        echo "API_URL"="${{ secrets.API_URL }}" > .env
        echo "DUMMY_USERNAME"="${{ secrets.DUMMY_USERNAME }}" >> .env
        echo "DUMMY_PASSWORD"="${{ secrets.DUMMY_PASSWORD }}" >> .env
        echo "SCOPE"="${{ secrets.SCOPE }}" >> .env
        echo "SECRET_KEY"="${{ secrets.SECRET_KEY }}" >> .env
        echo "TEST_USER_PWD"="${{ secrets.TEST_USER_PWD }}" >> .env
        echo "POSTGRES_USER"="${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD"="${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_HOST"="${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_TEST_DB_NAME"="${{ secrets.POSTGRES_TEST_DB_NAME }}" >> .env
        echo "POSTGRES_PORT"="${{ secrets.POSTGRES_PORT }}" >> .env
        echo "ADMIN_LOGIN"="${{ secrets.ADMIN_LOGIN }}" >> .env
        echo "ADMIN_PASSWORD"="${{ secrets.ADMIN_PASSWORD }}" >> .env
        echo "ADMIN_EMAIL"="${{ secrets.ADMIN_EMAIL }}" >> .env
        echo "BETTERSTACK_SOURCE_TOKEN"="${{ secrets.BETTERSTACK_SOURCE_TOKEN }}" >> .env

    - name: Update the project init submodule
      run: git submodule init

    - name: Update the project update submodule
      run: git submodule update

    - name: Build and push Docker images
      run: docker-compose build

    - name: Start Docker containers
      run: docker-compose up -d

    - name: sleep some time
      run: sleep 5

    - name: Run tests
      run: |
        docker exec bats bats 01-test_dummy_fastapi_token_routes.bats
        docker exec bats bats 02-test_dummy_fastapi_book_routes.bats
        docker exec bats bats 03-test_dummy_fastapi_user_routes.bats
        docker exec bats bats 04-test_dummy_fastapi_book_category_routes.bats
        docker exec bats bats 05-test_dummy_fastapi_comment_routes.bats
        docker exec bats bats 06-test_dummy_fastapi_quote_routes.bats
